## Get to know if any Service is running
services_status: null

## DeSOTA Services Configs
desota_services: {
    # DeSOTA models runner
    desotaai/derunner: {
        win: {
            service_path: Desota\DeRunner\executables\Windows,
            installer: https://github.com/desotaai/derunner/raw/main/Executables/Windows/DeRunner.install.bat,
            uninstaller: derunner.uninstall.bat,
            installer_args: [/reinstall],
            uninstaller_args: [/Q],
            starter: derunner.start.bat,
            stoper: derunner.stop.bat,
            version: 1.0.0
        },
        lin: {
            service_path: Desota\DeRunner\executables\Linux,
            installer: ,
            uninstaller: ,
            installer_args: ,+
            uninstaller_args: ,
            starter: ,
            stoper: ,
            version:
        },
        mac: {
            service_path: Desota\DeRunner\executables\MacOS,
            installer: ,
            uninstaller: ,
            installer_args: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            version:
            
        },
        description: Desota Models Runner,
        github: https://github.com/desotaai/derunner,
        run_constantly: true,
        submodel: false
    },
    # Models
    franciscomvargas/neuralqa/qa: {
        win: {
            service_path: Desota\Desota_Models\NeuraQA\neuralqa\executables\Windows,
            installer: https://raw.githubusercontent.com/franciscomvargas/neuralqa/master/neuralqa/executables/Windows/neuralqa.install.bat,
            uninstaller: neuralqa.uninstall.bat,
            installer_args: [/reinstall],
            uninstaller_args: [/Q],
            starter: neuralqa.start.bat,
            stoper: neuralqa.stop.bat,
            version: 1.0.0
        },
        lin: {
            service_path: Desota\Desota_Models\NeuraQA\neuralqa\executables\Linux,
            installer: ,
            uninstaller: ,
            installer_args: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            version:
        },
        mac: {
            service_path: Desota\Desota_Models\NeuraQA\neuralqa\executables\MacOS,
            installer: ,
            uninstaller: ,
            installer_args: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            version:
            
        },
        description: Library for Question Answering on Large Datasets with BERT,
        github: https://github.com/victordibia/neuralqa,
        run_constantly: false,
        submodel: false
    },
    franciscomvargas/neuralqa/expansion: {
        submodel: true,
        parentmodel: franciscomvargas/neuralqa/qa
    },
    franciscomvargas/descraper/url: {
        win: {
            service_path: Desota\Desota_Models\DeScraper\executables\Windows,
            installer: https://raw.githubusercontent.com/franciscomvargas/descraper/main/executables/Windows/descraper.install.bat,
            uninstaller: descraper.uninstall.bat,
            installer_args: [/reinstall],
            uninstaller_args: [/Q],
            starter: descraper.start.bat,
            stoper: descraper.stop.bat,
            version: 1.0.0
        },
        lin: {
            service_path: Desota\Desota_Models\DeScraper\executables\Linux,
            installer: ,
            uninstaller: ,
            installer_args: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            version:
        },
        mac: {
            service_path: Desota\Desota_Models\DeScraper\executables\MacOS,
            installer: ,
            uninstaller: ,
            installer_args: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            version:
            
        },
        description: WebScrape with assistance of AI Models,
        github: https://github.com/franciscomvargas/descraper,
        run_constantly: false,
        submodel: false
    },
    franciscomvargas/descraper/html: {
        submodel: true,
        parentmodel: franciscomvargas/descraper/url
    },
}
